#!/bin/sh
#
# (c) 2021 Yoichi Tanibayashi
#

ENV_FILE="$HOME/musicbox-env"

. $ENV_FILE

export MUSICBOX_WAVDIR=$MUSICBOX_DIR/wav
export MUSICBOX_WEBDIR_CALIBRATION=$MUSICBOX_DIR/web-calibration

export PYGAME_HIDE_SUPPORT_PROMPT=hide

if [ -z $VIRTUAL_ENV ]; then
   if [ -f $ENV_FILE ]; then
       . $VENVDIR/bin/activate
   else
       echo
       echo "ERROR(venv): can not activate python3 Virtualenv"
       echo
    exit 1
   fi
fi

# cd $MUSICBOX_DIR
exec python -m musicbox $*

### Local Variables: ***
### mode:shell-script ***
### End: ***
