#!/bin/sh
#
# (c) 2021 Yoichi Tanibayashi
#

ENV_FILE="$HOME/musicbox-env"

. $ENV_FILE

export MUSICBOX_WAV_DIR=$MUSICBOX_DIR/wav
export MUSICBOX_WEB_DIR=$MUSICBOX_DIR/web-root

export PYGAME_HIDE_SUPPORT_PROMPT=hide

if [ -z $VIRTUAL_ENV ]; then
   if [ -f $VENVDIR/bin/activate ]; then
       . $VENVDIR/bin/activate
   else
       echo
       echo "ERROR(venv): can not activate python3 Virtualenv"
       echo
    exit 1
   fi
fi

exec python -m musicbox $*

### Local Variables: ***
### mode:shell-script ***
### End: ***
